# ==============================================================================
# ==============================================================================
glint_site_testen:            true
glint_use_eleventy:           false
glint_url_abs:                "" 
glint_url_rel:                "" 
# ==============================================================================
# Gems
plugins_dir:
  - jekyll-paginate
# ==============================================================================
# Build settings
markdown: kramdown
# ==============================================================================
# ==============================================================================
