backend:
  name: git-gateway
  branch: master   # Branch to update (optional; defaults to master)

# adds an interface for drafting, reviewing, and approving posts.
publish_mode: editorial_workflow

# Media files will be stored in the repo under images/uploads
media_folder: "assets/images/uploads" 

collections:
  - name: "blocken_01"   # Used in routes, e.g., /admin/collections/blog
    label: "Blocken 01"  # Used in the UI
    folder: "_posts/blocken_01"   # The path to the folder where the documents are stored
    create: true   # Allow users to create new documents in this collection 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"   # Filename template, e.g., YYYY-MM-DD-title.md 
    fields:   # The fields for each document, usually in front matter 
      - { label: "Tags", name: "tags", widget:  "hidden", default: "block_01" }
      - { label: "Titel", name: "kop", widget: "string" }
      - { label: "Foto Md", name: "foto_bestand", widget: "image" }    
      - { label: "Alternatieve naam van de afbeelding", name: "foto_alt", required: false, widget: "string" }     
      - { label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic"], sanitize_preview: true }      
  - name: "carousels_01" 
    label: "Carousels 01"
    folder: "_posts/carousels_01" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - { label: "Tags", name: "tags", widget:  "hidden", default: "carousel_01" }    
      - { label: "Foto Xl", name: "foto_bestand", widget: "image" }
      - { label: "Alternatieve naam van de afbeelding", name: "foto_alt", required: false, widget: "string" } 
      - { label: "Tekst die op de afbeelding geplaatst wordt", name: "foto_tekst", widget: "string" }   
  - name: "openingstijd" 
    label: "Openingstijd"
    folder: "_posts/openingstijd" 
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - { label: "Tags", name: "tags", widget:  "hidden", default: "openingstijd" }    
      - { label: "Vakantie", name: "vakantie_tijd", widget: "boolean", default: false }    
  